### ISSUE TITLE
Did this work on ESXI or it will  only work on VCenter 

### ISSUE THREAD

**Issue by karthikkonar24** [Jannos-443/PRTG-VMware-Snapshot#3]
I have some queries could you please help me with that?
- Do we need to mention the server name, user name, and password inside the script.
- Did this below script does support ESXi Server.
- while calling the parameter do we need to mention the protocol like below
PRTG-VMware-Snapshot.ps1 -ViServer '%https://abc.domain.com%' -User '%test%' -Password '%Pass@123%'

Thanks,
Karthik Yadav.

**Comment by Jannos-443** [comment]
Hello Karthik,

> Do we need to mention the server name, user name, and password inside the script.

You could but i would prefer to just put the User and Password in the PRTG Parameters.

> Did this below script does support ESXi Server.

We are using it with a vcenter.

> while calling the parameter do we need to mention the protocol like below
> PRTG-VMware-Snapshot.ps1 -ViServer '%https://abc.domain.com%' -User '%test%' -Password '%Pass@123%'

You have to put the Hostname/FQDN as VIServer, please also remove all % in the Call.
PRTG-VMware-Snapshot.ps1 -ViServer 'abc.domain.com' -User 'test' -Password 'Pass@123'

Best regards
