### ISSUE TITLE
Sensor Error 

### ISSUE THREAD

**Issue by bonneau21** [Jannos-443/PRTG-VMware-Snapshot#4]
Hello i'm trying to use your script and get this error in the sensor 

XML: Junk after document element </prtg> -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

**Comment by Jannos-443** [comment]
Hello could you please run the Script in Powershell and show me you Parameter and Output?

**Comment by bonneau21** [comment]
I've upgraded PRTG to the last version and now it working fine
