### ISSUE TITLE
ExcludeSnapshotName does not work

### ISSUE THREAD

**Issue by vomHohenstein** [Jannos-443/PRTG-VMware-Snapshot#6]
I tried to use the parameter `-ExcludeSnapshotName 'name'` but it is ignored... anything I could try? Thank you! great script anyway! Michael

**Comment by Jannos-443** [comment]
Hey, please try using `-ExcludeSnapName '^(VMname1|VMname2)$'` instead of `-ExcludeSnapshotName 'name'`

**Comment by vomHohenstein** [comment]
Perfect! Works for me now! Great Support - Good job!
