### ISSUE TITLE
Invalid JSON error

### ISSUE THREAD

**Issue by AciDCooL** [Jannos-443/PRTG-VMware-Snapshot#8]
Hi I tried the script but it gives me Invalid JSON error, and no way to debug this, this is the debug form the script:

`The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx 
   ception
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
 
`

Since there are no line numbers where stuff is going wrong I have no idea how to fix this.
Manually executing the script works like a charm but only from PRTG there is this issue.

**Comment by Jannos-443** [comment]
Hi,

there should always be a line number if the script fails.
Could you check your PRTG Parameters and maybe post it here?

Best regards

**Comment by AciDCooL** [comment]
Hi,

Sorry for the long wait, took time off and the holidays had something to do with it :) I revisited it, and the problem lies in how passwords are handled in the script. apparently when there are special characters that are not escaped prtg outputs something without a line number. Nice work on the script btw! Have a good one.
