### ISSUE TITLE
VM Name leer

### ISSUE THREAD

**Issue by 01patrick** [Jannos-443/PRTG-VMware-Snapshot#9]
Hallo,

danke erstmal für das Skript dies hilft uns sehr.

Kann es sein dass eine VM, bei der der Name leer ist (siehe Bild), die Snapshots nicht mit erfasst werden?
![image](https://user-images.githubusercontent.com/126452941/221510825-37b85d79-0ee1-4660-95a2-3d4741f6f5bb.png)

VG
Patrick

**Comment by Jannos-443** [comment]
Hi Patrick,

bekommst du einen Fehler oder wird der Snapshot nur nicht aufgelistet?
Kannst du bitte die benutzten Parameter und den Logging Output einmal hier posten?

**Comment by 01patrick** [comment]
Hi Jannos,

Anbei der Befehl + Fehler

 C:\Temp> .\PRTG-VMware-Snapshot.ps1 -ViServer SERVER -Password ******** -User *********
<prtg>
<error>1</error>
<text>line:331 char:5 --- message: Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat. --- line:     $name = ($Snap.VM).ToString()
</text>
</prtg>

C:\Temp>

Wie gesagt ich denke das liegt daran das der VM-Name leer ist.

Was hältst du davon, wenn wir es mal mit der VM ID testen, die sollte immer vorhanden sein.
***@***.***

Ich kann die leider nicht erklären, warum der Name leer ist ☹


Mit freundlichen Grüßen / With best regards

Patrick

**Comment by Jannos-443** [comment]
sollte mit der neuen Version jetzt funktionieren, bitte mal testen.

**Comment by 01patrick** [comment]
Hi,

super passt jetzt.

Danke dir und noch eine schöne Woche.


Mit freundlichen Grüßen / With best regards

Patrick
